[package]
name = "tauri-plugin-context-menu"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.59"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.2.4" }
serde = { version = "1.0", features = ["derive"] }
cocoa = "0.24.1"
objc = "0.2.7"
dispatch = "0.2.0"
once_cell = "1.18.0"
block = "0.1.6"
libc = "0.2.147"
lazy_static = "1.4"
